[package]
name = "test_macro_expander_rustc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
ring = "0.16.20"
data-encoding = "2.4.0"
